# Change these first
owner: twelvebit-io # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Swapsicle Application
    url: https://app.swapsicle.io/swap
  - name: Swapsicle Landing
    url: https://www.swapsicle.io/
  - name: Swapsicle V1
    url: https://v1.swapsicle.io/
  - name: Swapsicle Analytics
    url: https://analytics.swapsicle.io/
  - name: Twelvebit
    url: https://twelvebit.io/
  - name: Sambuca
    url: https://sambucarestaurants.co.uk/
  - name: TelosX Landing
    url: https://telosx.io/
  

assignees: # Users to assign downtime issues (optional)
  - rozzaswap

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.twelvebit.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Twelvebit Uptime
  introTitle: "**Twelvebit Uptime**, our open-source uptime monitor and status page powered by GitHub Actions, Issues, and Pages."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
